CREATE TABLE CATEGORY (
  ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE MANUFACTURER (
  ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE IMAGE (
  ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
  SMALL_SIZE_IMAGE  VARCHAR(50)  NOT NULL,
  MEDIUM_SIZE_IMAGE VARCHAR(50)  NOT NULL,
  LARGE_SIZE_IMAGE  VARCHAR(50)  NOT NULL,
  DESCRIPTION       VARCHAR(100) NOT NULL
);

create TABLE PRODUCT (
  ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
  MANUFACTURER_ID BIGINT       NOT NULL,
  NAME            VARCHAR(100) NOT NULL,
  DESCRIPTION     CLOB(2000),
  SPECIFICATIONS  CLOB(2000),
  PRICE           DECIMAL      NOT NULL,

  FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER (ID)
);

CREATE TABLE CATEGORY_PRODUCT (
  CATEGORY_ID BIGINT NOT NULL,
  PRODUCT_ID  BIGINT NOT NULL,

  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE IMAGE_PRODUCT (
  IMAGE_ID   BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,

  FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
